### PR TITLE
Terminal colors

### PR DESCRIPTION
**Pull request by dimondjik**
No conflicts now! I'll close previous PR

### CODE REVIEW

**Comment by dimondjik** [comment]
The history is dirty, but the files are clean now

**Comment by hudson-ai** [comment]
Thanks @dimondjik ! My apologies again for not getting this all merged through yet. Still looking into alternatives to the current approach to keeping track of internal state in the model. Will keep you in the loop :)

**Comment by dimondjik** [comment]
No worries! As of now I also grew excited about terminal colors in the official release, so let me know if I could help :)

**Comment by hudson-ai** [comment]
@dimondjik I'm cherry-picking your commits rather than merging with dirty history just to avoid confusing myself -- don't worry, you're getting authorship ;)

I might roll back the state_list aspect of these changes, primarily keeping the output formatting class (with the very nice rgb to ANSI logic!). The state_list is a great idea, but I'm wary of the kind of double-bookkeeping that it's causing. IMO *everything* should be in that state list, and I have an open PR for that, but I expect that to have to go through several iterations before it's good enough to see the light of day.

Sorry for making you wait on this, and hopefully I can drive things forward before too long :)

**Comment by dimondjik** [comment]
@hudson-ai Nice! Sorry again for the history 😅 Glad to see that sweet ansi, as far as I researched that should work on non-custom terminals, colored lib also uses ansii escapes, so I'm 95% sure it is cross-platform. Good luck to you and your team wih state refactor!!

**Pull request closed without merging**
